# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruck-ugen}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Lieber"]
  s.date = %q{2010-07-10}
  s.default_executable = %q{ruck_ugen}
  s.description = %q{      A ruck shreduler and mini audio unit generator framework inspired by ChucK.
      Includes library for reading and writing multi-channel WAV files, and some
      basic audio filters.
}
  s.email = %q{tom@alltom.com}
  s.executables = ["ruck_ugen"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/ruck_ugen",
     "examples/ex01.rb",
     "examples/ex02.rb",
     "examples/ex03.rb",
     "examples/ex04.rb",
     "examples/ex05.rb",
     "examples/ex06.rb",
     "examples/ex07.rb",
     "examples/ex08.rb",
     "examples/ex09.rb",
     "examples/ex10.rb",
     "examples/ex11.rb",
     "lib/ruck/misc/linkage.rb",
     "lib/ruck/misc/riff.rb",
     "lib/ruck/ugen.rb",
     "lib/ruck/ugen/basic.rb",
     "lib/ruck/ugen/oscillators.rb",
     "lib/ruck/ugen/time_helpers.rb",
     "lib/ruck/ugen/ugen.rb",
     "lib/ruck/ugen/wav.rb",
     "ruck-ugen.gemspec",
     "test/bench.rb"
  ]
  s.homepage = %q{http://github.com/alltom/ruck-ugen}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ruck shreduler + mini audio unit generator framework inspired by ChucK}
  s.test_files = [
    "test/bench.rb",
     "examples/ex01.rb",
     "examples/ex02.rb",
     "examples/ex03.rb",
     "examples/ex04.rb",
     "examples/ex05.rb",
     "examples/ex06.rb",
     "examples/ex07.rb",
     "examples/ex08.rb",
     "examples/ex09.rb",
     "examples/ex10.rb",
     "examples/ex11.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruck>, [">= 0"])
    else
      s.add_dependency(%q<ruck>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruck>, [">= 0"])
  end
end

